import { Major } from './types';

export const SPECIALIZATIONS: Record<Major, string[]> = {
  [Major.AIDS]: [
    "Machine Learning Engineering",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing (NLP)",
    "Robotics",
    "Reinforcement Learning",
    "Data Engineering",
    "MLOps (Machine Learning Operations)",
    "Generative AI",
    "Time Series Analysis & Forecasting",
    "Recommender Systems",
    "Speech & Audio Processing",
    "Autonomous Systems (Self-Driving)",
    "Healthcare AI / Bioinformatics",
    "Cybersecurity AI",
    "Edge AI & IoT",
    "Financial AI (FinTech)",
    "Explainable AI (XAI)",
    "Research Scientist (AI Research)",
    "Data Science (Analytics & Business Intelligence)",
  ],
  [Major.CSCYS]: [
    "Software Engineering/Development",
    "Web Development (Frontend/Backend/Full-Stack)",
    "Mobile App Development",
    "DevOps/Site Reliability Engineering (SRE)",
    "Cloud Computing/Cloud Architecture",
    "Database Administration/Engineering",
    "Systems Programming",
    "Embedded Systems",
    "Game Development",
    "Computer Networks/Network Engineering",
    "Distributed Systems",
    "Computer Graphics",
    "Human-Computer Interaction (HCI)",
    "Blockchain Development",
    "Quantum Computing",
    "High-Performance Computing (HPC)",
    "Computer Architecture",
    "Compiler Design",
    "Operating Systems Development",
    "UI/UX Design (Technical)",
    "Penetration Testing (Ethical Hacking)",
    "Security Operations Center (SOC) Analyst",
    "Incident Response",
    "Digital Forensics",
    "Malware Analysis/Reverse Engineering",
    "Application Security (AppSec)",
    "Network Security",
    "Cloud Security",
    "Security Architecture",
    "Vulnerability Assessment",
    "Threat Intelligence",
    "Cryptography",
    "Security Compliance/Governance (GRC)",
    "Identity and Access Management (IAM)",
    "Red Team Operations",
    "Blue Team Operations",
    "Purple Team (Hybrid)",
    "IoT Security",
    "Mobile Security",
    "Security Engineering/DevSecOps",
  ],
  [Major.CISBIT]: [
    "Business Analysis",
    "IT Project Management",
    "Systems Analysis & Design",
    "Enterprise Resource Planning (ERP) Systems",
    "Business Intelligence (BI) & Analytics",
    "IT Consulting",
    "Database Management & Administration",
    "Enterprise Architecture",
    "IT Service Management (ITSM)",
    "Supply Chain Information Systems",
    "Customer Relationship Management (CRM) Systems",
    "E-Commerce & Digital Business",
    "Health Information Systems",
    "Financial Information Systems",
    "IT Governance & Compliance",
    "Business Process Management (BPM)",
    "IT Audit",
    "Knowledge Management Systems",
    "IT Strategy & Planning",
    "Digital Transformation",
    "IT Risk Management",
    "IT Vendor Management",
    "Enterprise Integration",
    "IT Operations Management",
    "IT Quality Assurance",
    "Product Management (Technical)",
    "Solutions Architecture",
    "Data Governance",
    "IT Asset Management",
    "Change Management (IT)",
  ],
};
